name: CI

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.1

            - name: Build
              run: |
                  npm install --legacy-peer-deps
                  npm run-script build
              env:
                  REACT_APP_BACK_URL: ${{ secrets.REACT_APP_BACK_URL }}

            - name: Deploy
              uses: JamesIves/github-pages-deploy-action@4.1.5
              with:
                  branch: gh-pages
                  folder: build
